### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-middleman-adit#1]
Having global variables like this will weird behaviour for anyone who tried to use multiple of this module
https://github.com/bitfocus/companion-module-middleman-adit/blob/main/index.js#L7-L10

Please dont blindly call `this.actions()` on an interval like this https://github.com/bitfocus/companion-module-middleman-adit/blob/main/index.js#L48-L49. If there are changes, then that is ok, but you are forcing companion to do a lot of work to handle the 'new' list of actions every 5s, when it is likely nothing has changed

Have you considered using a better http client than `http`? `got` is my goto these days, but there are many others that give a much better api than `http`. This is completely up to you, you dont have to change it if you dont want to

**Comment by jheliker** [comment]
Thanks @Julusian!

Question, we're currently calling this.actions() in order to update the options list (drop down choices) available for the actions according to the data received from HTTP GET requests. Is there a better way to update the options lists? The actions themselves aren't changing, just the available options. 

Re global variables, I was under the (wrong) impression that each instance of a module was isolated. I'll move those to self if that works.

**Comment by Julusian** [comment]
There isn't currently a better way. calling `this.actions()` is fine to do (many of my modules have to do the same thing), but just try to limit how often you call it. Doing so on an interval is excessive
